import * as XLSX from "xlsx";
// eslint-disable-next-line react/prop-types
export const BottonExportItems = ({ datos }) => {
  const titulo = [{ A: "Reporte de arqueo" }, {}];
  const hora = new Date();
  const infoCreacción = { A: `Fecha De Creación ${hora}` };
  const longitudes = [25, 25, 20, 10, 10, 10, 35];

  const handleDownload = () => {
    const tabla = datos.map((item) => ({
      A: item.supervisor,
      B: item.nombres,
      C: item.nombre_supervisor,
      D: item.documento,
      E: item.ip,
      F: item.sucursal,
      G: item.puntodeventa,
      H: item.ventabruta,
      I: item.baseefectivo,
      J: item.totalingreso,
      K: item.chancesabonados,
      L: item.chancespreimpresos,
      M: item.premiospagados,
      N: item.efectivocajafuerte,
      O: item.totalegresos,
      P: item.totalbilletes,
      Q: item.totalmonedas,
      R: item.totalarqueo,
      S: item.sobrantefaltante,
      T: item.canti_billete_cienmil,
      U: item.total_billete_cienmil,
      V: item.canti_billete_cincuentamil,
      W: item.total_billete_cincuentamil,
      y: item.canti_billete_veintemil,
      Z: item.total_billete_veintemil,
      AB: item.canti_billete_diezmil,
      AC: item.total_billete_diezmil,
      AD: item.canti_billete_cincomil,
      AE: item.total_billete_cincomil,
      AF: item.canti_billete_dosmil,
      AG: item.total_billete_dosmil,
      AH: item.canti_billete_mil,
      AI: item.total_billete_mil,
      AJ: item.canti_moneda_mil,
      AK: item.total_moneda_mil,
      AL: item.canti_moneda_quinientos,
      AM: item.total_moneda_quinientos,
      AN: item.canti_moneda_docientos,
      AO: item.total_moneda_docientos,
      AQ: item.canti_moneda_cien,
      AR: item.total_moneda_cien,
      AS: item.canti_moneda_cincuenta,
      AT: item.total_moneda_ciencuenta,
      AU: item.total_efectivo,
      AV: item.total_premios_pagados,
      AW: item.entrega_colocador,
      AX: item.sobrantefaltante_caja,
      AY: item.colocador_cajafuerte,
      AZ: item.rollos_bnet,
      BA: item.rollos_fisicos,
      BB: item.diferencia,
      BC: item.nombre_juego,
      BD: item.cantidad_bnet,
      BE: item.cantidad_fisicos,
      BF: item.cantidad_faltante,
      BG: item.cantidad_tiquete,
      BH: item.descargado,
      BI: item.nombre_juego2,
      BJ: item.cantidad_bnet2,
      BK: item.cantidad_fisicos2,
      BL: item.cantidad_faltante2,
      BM: item.cantidad_tiquete2,
      BN: item.descargado2,
      BO: item.nombre_juego3,
      BP: item.cantidad_bnet3,
      BQ: item.cantidad_fisicos3,
      BR: item.cantidad_faltante3,
      BS: item.cantidad_tiquete3,
      BT: item.descargado3,
      BU: item.nombre_juego4,
      BV: item.cantidad_bnet4,
      BW: item.cantidad_fisicos4,
      BX: item.cantidad_faltante4,
      BY: item.cantidad_tiquete4,
      BZ: item.descargado4,
      CA: item.totaldescargados,
      CB: item.totalvalor,
      CC: item.requisito1,
      CD: item.observacion1,
      CE: item.requisito2,
      CF: item.observacion2,
      CG: item.requisito3,
      CH: item.observacion3,
      CI: item.requisito4,
      CJ: item.observacion4,
      CK: item.requisito5,
      CL: item.observacion5,
      CM: item.requisito6,
      CN: item.observacion6,
      CO: item.requisito7,
      CP: item.observacion7,
      CQ: item.requisito8,
      CR: item.observacion8,
      CS: item.requisito9,
      CT: item.observacion9,
      CU: item.requisito10,
      CV: item.observacion10,
      CW: item.requisito11,
      CX: item.observacion11,
      CY: item.requisito12,
      CZ: item.observacion12,
      DA: item.requisito13,
      DB: item.observacion13,
      DC: item.requisito14,
      DD: item.observacion14,
      DE: item.requisito15,
      DF: item.observacion15,
      DG: item.requisito16,
      DH: item.observacion16,
      DI: item.requisito17,
      DJ: item.observacion17,
      DK: item.requisito18,
      DL: item.observacion18,
      DM: item.requisito19,
      DN: item.observacion19,
      DO: item.requisito20,
      DP: item.observacion20,
      DQ: item.requisito21,
      DR: item.observacion21,
      DS: item.requisito22,
      DT: item.observacion22,
      DU: item.requisito23,
      DV: item.observacion23,
      DW: item.requisito24,
      DX: item.observacion24,
      DY: item.requisito25,
      DZ: item.observacion25,
      EA: item.requisito26,
      EB: item.observacion26,
      EC: item.requisito27,
      ED: item.observacion27,
      EE: item.requisito28,
      EF: item.observacion28,
      EG: item.requisito29,
      EH: item.requisito30,
      EI: item.fechavisita,
      EJ: item.horavisita,
      EK: item.latitud,
      EL: item.longitud,
    }));

    const columnNames = {
      A: "supervisor",
      B: "nombres",
      C: "nombre supervisor",
      D: "documento",
      E: "ip",
      F: "sucursal",
      G: "puntodeventa",
      H: "ventabruta ",
      I: "baseefectivo ",
      J: "totalingreso ",
      K: "chancesabonados ",
      L: "chancespreimpresos ",
      M: "premiospagados ",
      N: "efectivocajafuerte ",
      O: "totalegresos ",
      P: "totalbilletes ",
      Q: "totalmonedas ",
      R: "totalarqueo ",
      S: "sobrantefaltante: ",
      T: "canti_billete_cienmil ",
      U: "total_billete_cienmil ",
      V: "canti_billete_cincuentamil ",
      W: "total_billete_cincuentamil ",
      y: "canti_billete_veintemil ",
      Z: "total_billete_veintemil ",
      AB: "canti_billete_diezmil",
      AC: "total_billete_diezmil",
      AD: " canti_billete_cincomil ",
      AE: "total_billete_cincomil ",
      AF: "canti_billete_dosmil ",
      AG: "total_billete_dosmil ",
      AH: "canti_billete_mil ",
      AI: "total_billete_mil",
      AJ: "canti_moneda_mil",
      AK: "total_moneda_mil",
      AL: "canti_moneda_quinientos ",
      AM: "total_moneda_quinientos ",
      AN: "canti_moneda_docientos ",
      AO: "total_moneda_docientos ",
      AQ: "canti_moneda_cien",
      AR: "total_moneda_cien",
      AS: "canti_moneda_cincuenta ",
      AT: "total_moneda_ciencuenta ",
      AU: "total_efectivo ",
      AV: "total_premios_pagados",
      AW: "entrega_colocador ",
      AX: "sobrantefaltante_caja ",
      AY: "colocador_cajafuerte",
      AZ: "rollos_bnet ",
      BA: "rollos_fisicos ",
      BB: "diferencia ",
      BC: "nombre_juego ",
      BD: "cantidad_bnet ",
      BE: "cantidad_fisicos ",
      BF: " cantidad_faltante ",
      BG: "cantidad_tiquete ",
      BH: "descargado ",
      BI: "nombre_juego2 ",
      BJ: "cantidad_bnet2 ",
      BK: "cantidad_fisicos2 ",
      BL: "cantidad_faltante2 ",
      BM: "cantidad_tiquete2 ",
      BN: "descargado2 ",
      BO: "nombre_juego3 ",
      BP: "cantidad_bnet3 ",
      BQ: "cantidad_fisicos3 ",
      BR: "cantidad_faltante3 ",
      BS: "cantidad_tiquete3 ",
      BT: "descargado3 ",
      BU: "nombre_juego4 ",
      BV: "cantidad_bnet4 ",
      BW: "cantidad_fisicos4 ",
      BX: "cantidad_faltante4 ",
      BY: "cantidad_tiquete4 ",
      BZ: "descargado4 ",
      CA: "totaldescargados ",
      CB: "totalvalor ",
      CC: "requisito1 ",
      CD: "observacion1",
      CE: "requisito2 ",
      CF: "observacion2",
      CG: "requisito3 ",
      CH: "observacion3 ",
      CI: "requisito4 ",
      CJ: "observacion4 ",
      CK: "requisito5 ",
      CL: "observacion5 ",
      CM: "requisito6 ",
      CN: "observacion6 ",
      CO: "requisito7 ",
      CP: "observacion7 ",
      CQ: "requisito8 ",
      CR: "observacion8 ",
      CS: "requisito9 ",
      CT: "observacion9 ",
      CU: "requisito10 ",
      CV: "observacion10",
      CW: "requisito11 ",
      CX: "observacion11",
      CY: "requisito12 ",
      CZ: "observacion12",
      DA: "requisito13 ",
      DB: "observacion13",
      DC: "requisito14 ",
      DD: "observacion14",
      DE: "requisito15 ",
      DF: "observacion15",
      DG: "requisito16 ",
      DH: "observacion16",
      DI: "requisito17 ",
      DJ: "observacion17",
      DK: "requisito18 ",
      DL: "observacion18",
      DM: "requisito19 ",
      DN: "observacion19",
      DO: "requisito20 ",
      DP: "observacion20",
      DQ: "requisito21 ",
      DR: "observacion21",
      DS: "requisito22 ",
      DT: "observacion22",
      DU: "requisito23 ",
      DV: "observacion23",
      DW: "requisito24 ",
      DX: "observacion24",
      DY: "requisito25 ",
      DZ: "observacion25",
      EA: "requisito26 ",
      EB: "observacion26",
      EC: "requisito27 ",
      ED: "observacion27",
      EE: "requisito28 ",
      EF: "observacion28",
      EG: "requisito29 ",
      EH: "requisito30 ",
      EI: "fechavisita ",
      EJ: "horavisita ",
      EK: "latitud ",
      EL: "longitud ",
      // Continúa con el resto de nombres de las columnas
    };

    const dataFinal = [...titulo, infoCreacción, columnNames, ...tabla];

    setTimeout(() => {
      creandoArchivo(dataFinal);
    }, 1000);
  };

  const creandoArchivo = (dataFinal) => {
    const libro = XLSX.utils.book_new();
    const hoja = XLSX.utils.json_to_sheet(dataFinal, { skipHeader: true });

    hoja["!merges"] = [
      XLSX.utils.decode_range("A1:G1"),
      XLSX.utils.decode_range("A2:G2"),
      XLSX.utils.decode_range("A3:G3"),
    ];

    const simpiedades = [];

    longitudes.forEach((col) => {
      simpiedades.push({ width: col });
    });

    hoja["!cols"] = simpiedades;
    XLSX.utils.book_append_sheet(libro, hoja, "Items");
    XLSX.writeFile(libro, "datos.xlsx");
  };

  return (
    <div className="flex translate-y-4 translate-x-12 text-center font-bold uppercase mt-3">
      <button
        type="button"
        onClick={handleDownload}
        className="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded-lg "
      >
        Exportar a Excel
      </button>
    </div>
  );
};
